mysql:
  image: mariadb:5.5
  volumes:
    - ./mysql:/var/lib
  environment:
    MYSQL_ROOT_PASSWORD: wp
    MYSQL_DATABASE: wp
    MYSQL_USER: wp
    MYSQL_PASSWORD: wp

cron:
  build: .  
  command: crond -f -l 6 -L /dev/stdout
  volumes:
    - ./wp-content:/var/www/wp-content
  links:
    - mysql

wordpress:
  build: .  
  volumes:
    - ./wp-content:/var/www/wp-content
  ports:
    - 8080:80
  links:
    - mysql